// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Trade Items
export const ADD_TRADE_ITEM = "ADD_TRADE_ITEM";
export const REMOVE_TRADE_ITEM = "REMOVE_TRADE_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_CURRENT_ITEM = "CLEAR_CURRENT_ITEM";

// User
export const SET_USER = "SET_USER";
export const SET_TRADE_PARTNER = "SET_TRADE_PARTNER";
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_TRADE_PARTNER = "CLEAR_TRADE_PARTNER";

// Web3
export const CONNECT_WEB3 = "CONNECT_WEB3";
export const UPDATE_WEB3 = "UPDATE_WEB3";
export const ADD_CONTRACT_OBJECT = "ADD_CONTRACT_OBJECT";
export const REMOVE_CONTRACT_OBJECT = "REMOVE_CONTRACT_OBJECT";
export const CONTRACT_OBJECT_ERROR = "CONTRACT_OBJECT_ERROR";

// Ens

export const SET_UTIL_CONTRACT = "SET_UTIL_CONTRACT";