// App
export const SET_LOCATION = "SET_LOCATION";

// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Trade Items
export const SET_USER_BOX = "SET_USER_BOX";
export const ADD_TRADE_ITEM = "ADD_TRADE_ITEM";
export const REMOVE_TRADE_ITEM = "REMOVE_TRADE_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_CURRENT_ITEM = "CLEAR_CURRENT_ITEM";

export const UPDATE_ACCEPTED = "UPDATE_ACCEPTED";
export const SET_ACCEPTED = "SET_ACCEPTED";

// User
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_TRADE_PARTNER = "CLEAR_TRADE_PARTNER";
export const SET_ADDRESS = "SET_ADDRESS";
export const CLEAR_ADDRESS = "CLEAR_ADDRESS";
export const SET_BALANCE = "SET_BALANCE";
export const CLEAR_BALANCE = "CLEAR_BALANCE";
export const SET_OWNED_TOKENS = "SET_OWNED_TOKENS";
export const SET_REQUESTED_TOKENS = "SET_REQUESTED_TOKENS";
export const ADD_REQUESTED_TOKEN = "ADD_REQUESTED_TOKEN";
export const SET_SETTINGS = "SET_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const CLEAR_SETTINGS = "CLEAR_SETTINGS";

// Web3
export const CONNECT_WEB3 = "CONNECT_WEB3";
export const UPDATE_WEB3 = "UPDATE_WEB3";
export const ADD_CONTRACT_OBJECT = "ADD_CONTRACT_OBJECT";
export const REMOVE_CONTRACT_OBJECT = "REMOVE_CONTRACT_OBJECT";
export const CONTRACT_OBJECT_ERROR = "CONTRACT_OBJECT_ERROR";

// Ens
export const SET_UTIL_CONTRACT = "SET_UTIL_CONTRACT";
