// App
export const SET_LOCATION = "SET_LOCATION";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Alert
export const ADD_ALERT: string = "ADD_ALERT";
export const REMOVE_ALERT: string = "REMOVE_ALERT";
export const CLEAR_ALERTS: string = "CLEAR_ALERTS";

// Trade Items
export const SET_USER_BOX = "SET_USER_BOX";
export const ADD_TRADE_ITEM = "ADD_TRADE_ITEM";

export const SET_USER_ACCEPTED = "SET_USER_ACCEPTED";
export const SET_PARTNER_ACCEPTED = "SET_PARTNER_ACCEPTED";
export const SET_USER_TRADE_ITEMS = "SET_USER_TRADE_ITEMS";
export const SET_PARTNER_TRADE_ITEMS = "SET_PARTNER_TRADE_ITEMS";
export const REMOVE_TRADE_ITEM = "REMOVE_TRADE_ITEM";
export const MODIFY_TRADE_ITEM_STATUS = "MODIFY_TRADE_ITEM_STATUS";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_CURRENT_ITEM = "CLEAR_CURRENT_ITEM";

export const UPDATE_ACCEPTED = "UPDATE_ACCEPTED";
export const TOGGLE_ACCEPTED = "TOGGLE_ACCEPTED";

// User
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_TRADE_PARTNER = "CLEAR_TRADE_PARTNER";
export const SET_ADDRESSES = "SET_ADDRESSES";
export const CLEAR_ADDRESSES = "CLEAR_ADDRESSES";
export const SET_BALANCE = "SET_BALANCE";
export const CLEAR_BALANCE = "CLEAR_BALANCE";
export const SET_OWNED_TOKENS = "SET_OWNED_TOKENS";
export const SET_REQUESTED_TOKENS = "SET_REQUESTED_TOKENS";
export const ADD_REQUESTED_TOKEN = "ADD_REQUESTED_TOKEN";
export const SET_SETTINGS = "SET_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const CLEAR_SETTINGS = "CLEAR_SETTINGS";

// Web3
export const CONNECT = "CONNECT";
export const CONNECT_WEB3 = "CONNECT_WEB3";
export const CONNECT_ENS = "CONNECT_ENS";
export const DISCONNECT_WEB3 = "DISCONNECT_WEB3";
export const DISCONNECT_ENS = "DISCONNECT_ENS";
export const UPDATE_NETWORK = "UPDATE_NETWORK";
export const ADD_CONTRACT_OBJECT = "ADD_CONTRACT_OBJECT";
export const REMOVE_CONTRACT_OBJECT = "REMOVE_CONTRACT_OBJECT";
export const CONTRACT_OBJECT_ERROR = "CONTRACT_OBJECT_ERROR";

// Ens
export const SET_UTIL_CONTRACT = "SET_UTIL_CONTRACT";

export const SET_ARCA = "SET_ARCA";
export const ADD_ERC = "ADD_ERC";
export const DISCONNECT = "DISCONNECT";
//export const UPDATE_NETWORK = "UPDATE_NETWORK";
