// App
export const SET_LOCATION = "SET_LOCATION";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Alert
export const ADD_ALERT: string = "ADD_ALERT";
export const REMOVE_ALERT: string = "REMOVE_ALERT";
export const CLEAR_ALERTS: string = "CLEAR_ALERTS";

// Trade Items
export const SET_USER_BOX = "SET_USER_BOX";
export const ADD_TRADE_ITEM = "ADD_TRADE_ITEM";

export const SET_USER_ACCEPTED = "SET_USER_ACCEPTED";
export const SET_PARTNER_ACCEPTED = "SET_PARTNER_ACCEPTED";
export const SET_USER_TRADE_ITEMS = "SET_USER_TRADE_ITEMS";
export const SET_PARTNER_TRADE_ITEMS = "SET_PARTNER_TRADE_ITEMS";
export const REMOVE_TRADE_ITEM = "REMOVE_TRADE_ITEM";
export const MODIFY_TRADE_ITEM_STATUS = "MODIFY_TRADE_ITEM_STATUS";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_CURRENT_ITEM = "CLEAR_CURRENT_ITEM";

export const UPDATE_ACCEPTED = "UPDATE_ACCEPTED";
export const TOGGLE_ACCEPTED = "TOGGLE_ACCEPTED";

// User / Partner
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_BALANCE = "SET_BALANCE";
export const SET_ERC20S = "SET_ERC20S";
export const SET_ERC721S = "SET_ERC721S";

// Web3
export const ADD_PROVIDER = "ADD_PROVIDER";
export const ADD_SIGNER = "ADD_SIGNER";
export const SET_ARCA_ADDRESS = "SET_ARCA_ADDRESS";
export const SET_ARCA_CONTRACT = "SET_ARCA_CONTRACT";
export const SET_ERC20_ADDRESSES = "SET_ERC20_ADDRESSES";
export const SET_ERC721_ADDRESSES = "SET_ERC721_ADDRESSES";

// Ens
export const SET_UTIL_CONTRACT = "SET_UTIL_CONTRACT";

export const SET_ARCA = "SET_ARCA";
export const ADD_ERC = "ADD_ERC";
export const DISCONNECT = "DISCONNECT";
//export const UPDATE_NETWORK = "UPDATE_NETWORK";
